-- HimalCyberX Security Hardening — RECOMMENDED RLS CHANGES
-- =============================================================================
-- IMPLEMENTED BUNDLE: supabase/v2-admin-rls-foundation.sql
-- ONE-TIME ROLE SETUP: supabase/v2-admin-role-setup.sql
--
-- DO NOT RUN AUTOMATICALLY. Review and apply manually in the Supabase SQL editor.
-- This file documents the approach; use v2-admin-rls-foundation.sql for deployment.
-- =============================================================================

-- Helper: true when JWT carries hcx_admin role
-- CREATE OR REPLACE FUNCTION public.is_hcx_admin()
-- RETURNS boolean
-- LANGUAGE sql
-- STABLE
-- AS $$
--   SELECT coalesce(
--     (auth.jwt() -> 'app_metadata' ->> 'role') = 'hcx_admin',
--     false
--   );
-- $$;

-- ---------------------------------------------------------------------------
-- EXAMPLE: Replace broad article admin policies
-- ---------------------------------------------------------------------------
-- DROP POLICY IF EXISTS "Authenticated users can read all articles" ON public.articles;
-- DROP POLICY IF EXISTS "Authenticated users can insert articles" ON public.articles;
-- DROP POLICY IF EXISTS "Authenticated users can update articles" ON public.articles;
-- DROP POLICY IF EXISTS "Authenticated users can delete articles" ON public.articles;
--
-- CREATE POLICY "HCX admin can read all articles"
-- ON public.articles FOR SELECT TO authenticated
-- USING (public.is_hcx_admin());
--
-- CREATE POLICY "HCX admin can insert articles"
-- ON public.articles FOR INSERT TO authenticated
-- WITH CHECK (public.is_hcx_admin());
--
-- CREATE POLICY "HCX admin can update articles"
-- ON public.articles FOR UPDATE TO authenticated
-- USING (public.is_hcx_admin()) WITH CHECK (public.is_hcx_admin());
--
-- CREATE POLICY "HCX admin can delete articles"
-- ON public.articles FOR DELETE TO authenticated
-- USING (public.is_hcx_admin());

-- ---------------------------------------------------------------------------
-- Apply the same pattern to:
--   public.categories
--   public.labs
--   public.tutorials
--   public.subscribers  (admin SELECT/UPDATE only; keep public INSERT policy)
--   public.messages     (admin SELECT/UPDATE only; keep public INSERT policy)
--   public.site_settings (admin INSERT/UPDATE only; keep public SELECT policy)
--   storage.objects     (article-images bucket upload/delete for hcx_admin only)
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- Policies that are correctly scoped today (keep as-is):
-- ---------------------------------------------------------------------------
-- articles:  anon SELECT WHERE status = 'published'
-- labs:      anon SELECT WHERE status = 'published'
-- tutorials: anon SELECT WHERE status = 'published'
-- subscribers: anon INSERT WITH CHECK (status = 'active' AND source IN (...))
-- messages:  anon INSERT WITH CHECK (status = 'new')
-- site_settings: anon SELECT (public branding/SEO — intentional)
-- categories: anon SELECT (used for public article metadata)

-- ---------------------------------------------------------------------------
-- Optional hardening (review impact first):
-- ---------------------------------------------------------------------------
-- 1. Remove authenticated DELETE on subscribers if soft-unsubscribe is sufficient
-- 2. Add CHECK constraints on message/subscriber field lengths at DB level
-- 3. Rate-limit contact/newsletter via Supabase Edge Functions or Vercel middleware
-- 4. Disable public sign-ups in Supabase Auth (invite-only admin account)
